[package]
name = "ani-gif"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.3.10"
gif = "0.12.0"
gif-dispose = "4.0.0"
riff-ani = "0.1.0"
